#base
server:
  port: 8761
spring:
  profiles:
    active: native, local
  application:
    name: discovery
info:
  application:
    name: @project.artifactId@
    version: @project.version@

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false