info:
  application:
    name: @project.artifactId@
    version: @project.version@

spring:
  profiles:
    active: local
  application:
    name: test
  config:
    import: optional:configserver:http://localhost:8760