server:
  port: 8760

info:
  application:
    name: @project.artifactId@
    version: @project.version@

spring:
  application:
    name: config
  profiles:
    active: native, local
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/common

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: false