server:
  port: 8760

info:
  application:
    name: @project.artifactId@
    version: @project.version@

spring:
  application:
    name: config
  profiles:
    active: native, local
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/common

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p){} <> %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p <> %-40.40logger{39} : %m%n%wEx"
  file:
    #Disable logging
    path:
  level:
    root: info

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: false